version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Check python verison
          command: python --version
  publish-documentation:
    steps:
      - run:
          name: Publish documentation
          command: echo "publish documentation"
  other-job:
    steps:
      - run:
          name: Do something
          command: echo "Doing something"


workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
      - publish-documentation:
          requires:
            - build-and-test
      - other-job:
          requires:
            - build-and-test
